### ISSUE TITLE
Wrong assignment or prolines?

### ISSUE THREAD

**Issue by marinegor** [ShintaroMinami/PyDSSP#2]
Hi, thanks a lot for the implementation -- this is what many people have been missing, apparently :)

Could you please help me figure out the issue with prolines: as far as I see, they can get assigned both 'H' and 'E' type in your implementation. However, afaik they don't participate in either beta-strand or alpha-helix type of bonds (at least as donors), since they lack `H` atom on the backbone `N`.

Am I right that it's better to manually set all prolines to `-` after `pydssp` for better correctness?

**Comment by ShintaroMinami** [comment]
So sorry for delayed reply. I fixed Proline issue by ignoring N-H donor effect of proline on the h-bond map. Thank you so much for your help to improve the repo!!

**Comment by ShintaroMinami** [comment]
This issue was fixed in the current version

**Comment by marinegor** [comment]
thanks for the fix! no worries, I understand that things may move slow in the open-source :)

fyi, I've [integrated](https://github.com/MDAnalysis/mdanalysis/pull/4304) your pydssp code into [MDAnalysis](https://github.com/MDAnalysis/mdanalysis/) software package some time ago. I haven't looked into the proline fix yet, but if you're interested in contributing it upstream, hit me up, I'll be happy to help!
